### ISSUE TITLE
Display subquorum avaliability for entities

### ISSUE THREAD

**Issue by tomerweller** [stellarbeat/js-stellarbeat-frontend#10]
To asses the quality of an entity (#7), it's helpful to know the availability of it as a subquorum, containing all of it's validators.

For example, if the entity has 3 validators, It's considered up as long it has 2 validators up. (up = validating and in sync)

**Comment by pieterjan84** [comment]
Ok so an organization as subquorum(set) would fail when it no longer reaches a majority threshold calculated by: Math.floor(nrOfValidators - (nrOfValidators - 1) / 2). 
I could add a subquorum availability status with three states: ok, warning and danger. Danger means the subquorum is failing. Warning means if only one validator fails, the subquorum fails. And 'ok' means more then 1 validator can fail before the subquorum fails. For example:
<img width="758" alt="Schermafbeelding 2019-06-25 om 21 10 37" src="https://user-images.githubusercontent.com/35334552/60126583-9c9a0300-978e-11e9-95a6-66aae041546b.png">
What do you think?

**Comment by jedmccaleb** [comment]
Wouldn't you just look at the threshold of the subquorum and compare that to how many vadilators are active in the subquorum? Not all the subs will have threshold of 51%

**Comment by pieterjan84** [comment]
Added subquorum availability to organization table.
