### ISSUE TITLE
transitive quorum set analysis

### ISSUE THREAD

**Issue by tomerweller** [stellarbeat/js-stellarbeat-frontend#11]
It might be difficult to distinguish the network's transitive quorum set from other strongly connected components (a subgraph in which every node is reachable from every other node). For example, Sui's cluster is strongly connected, but is not part of the transitive quorum set.

You can use a known algorithm to partition the graph into strongly connected components. (@MonsieurNicolas suggests [Tarjan's](https://en.wikipedia.org/wiki/Tarjan's_strongly_connected_components_algorithm))

If the network is configured properly there should only be one component that has no outgoing edges. That is the transitive quorum set.

If there is more than one component that meets that description you need to disambiguate. That's pretty subjective. You will need to choose one based on trust, either ask the user, or preselect a node that is likely to be in the transitive quorum set. 

Once you figure out the transitive quorum set you can visualize it by clustering these nodes or giving them a different style.

**Comment by pieterjan84** [comment]
I implemented Tarjan's algorithm and have a first version almost ready.

When there are multiple transitive quorum sets candidates, the one with the highest network index/trust is selected as transitive quorum. The other candidates are visualized/identified as 'plain' strongly connected components.

For the visualization I chose to use thicker edges for strongly connected components (e.g. Wirex) and a transparent blue background for the transitive quorum set:
<img width="648" alt="transitive quorum set" src="https://user-images.githubusercontent.com/35334552/63044878-714ead00-becf-11e9-8b38-9da1ad839a4b.png">


I also did some tweaks to the visualization so you can more clearly see that there are for example no outgoing edges (orange edges) in the transitive quorum set, for example when you select a keybase validator:
<img width="544" alt="transitive quorum set with selection" src="https://user-images.githubusercontent.com/35334552/63044891-76abf780-becf-11e9-9071-7bb99a028924.png">


Let me know if you have any thoughts or remarks.

**Comment by MonsieurNicolas** [comment]
Just one remark: this is super cool!

**Comment by pieterjan84** [comment]
Released: https://stellarbeat.io/quorum-monitor
