### ISSUE TITLE
Add a generate quorum set configuration feature

### ISSUE THREAD

**Issue by brahman81** [stellarbeat/js-stellarbeat-frontend#13]
When looking at the Quorum Monitor on stellarbeat.io it defaults to displaying the "Network transitive quorumset" as a list of nodes. At present one has to drill down into the individual node details to extract Public Key, History Archive, Home Domain, etc, to create their own Quorum Set configuration.

It would be ideal to have quick way to generate `[[VALIDATOR]]` config stanzas from the default "Network transitive quorumset" list, that users could then simply append to their existing `stellar-core.cfg`.

**Comment by pieterjan84** [comment]
Added an export button for the quorum set configuration and marked all 'tier one' organization validators with quality 'HIGH'.  Other validators are marked with quality 'MEDIUM_OR_LOW', and is up for the user to decide (for now). Let me know if you have any suggestions.
