### ISSUE TITLE
Validating stats chart is not perfectly readable

### ISSUE THREAD

**Issue by s-a-y** [stellarbeat/js-stellarbeat-frontend#16]
Hey, small issue, but would be good if chart at the end of the node page was more representative.
Here's node stats, looks ok, there is no red
<img width="461" alt="Screen Shot 2020-03-06 at 11 21 22 AM" src="https://user-images.githubusercontent.com/1667781/76038084-d1588e00-5f9c-11ea-8d51-66d0b1b3bbea.png">

But in fact there is a small percentage of downtime hiding there
<img width="475" alt="Screen Shot 2020-03-06 at 11 21 19 AM" src="https://user-images.githubusercontent.com/1667781/76038088-d4ec1500-5f9c-11ea-9eeb-2d4165b4e9af.png">

I wish there was a way to see it more clearly

**Comment by pieterjan84** [comment]
Time points that have less then 100% now have a lighter shade of green. Thank you for your feedback!
