### ISSUE TITLE
Group validators by entities

### ISSUE THREAD

**Issue by tomerweller** [stellarbeat/js-stellarbeat-frontend#7]
As trust in the network evolves, it becomes important to put trust in entities, rather than individual validators.

We can assume that validators that share the same home domain (sep20) belong to the same entity and we can get further information about that entity from the home domain. 

Some low hanging fruit: 
- Add entity field to the node list. 
- In the monitor offer links to other validators in the same entity

Longer term, treat entities as first class objects: 
- Have a dedicated entity list with entity level metrics: average availability, validator count, etc.  
- Have entity clusters in the explorer view.

**Comment by pieterjan84** [comment]
Started tracking organizations and added organization field to node list.

**Comment by pitsevich** [comment]
That's nice!

Would also be great to be able to filter by organization in the URL.
So that organizations could share a link to a set of validators managed by them, e.g. 
https://stellarbeat.io/nodes?org=ACME%20Inc.

**Comment by pieterjan84** [comment]
Added organization table and info endpoints. Added organization to quorum monitor.
@pitsevich for example: https://stellarbeat.io/organizations/ad733706cebb901f8b8cbb1b6a9bb785

Todo: metrics

**Comment by pitsevich** [comment]
Thats awesome!! We will put the link in our toml file!

**Comment by pieterjan84** [comment]
Added organization name to subquorum that contains only validators of a certain organization in quorum monitor.
