### ISSUE TITLE
Add ability to filter by node in /nodes API

### ISSUE THREAD

**Issue by pitsevich** [stellarbeat/js-stellarbeat-frontend#8]
It would be good to be able to fetch information related to a specific node, e.g.

https://api.stellarbeat.io/v1/nodes?publicKey=GA7TEPCBDQKI7JQLQ34ZURRMK44DVYCIGVXQQWNSWAEQR6KB4FMCBT7J

That would allow to setup simple alerts using services like Pingdom that trigger when your node stops validating by verifying that the response has `"isValidating":true`

**Comment by pieterjan84** [comment]
Added nodes/:publicKey and organizations/:id
 for example:
https://api.stellarbeat.io/v1/nodes/GCFONE23AB7Y6C5YZOMKUKGETPIAJA4QOYLS5VNS4JHBGKRZCPYHDLW7
and
https://api.stellarbeat.io/v1/organizations/ad733706cebb901f8b8cbb1b6a9bb785
